version: "3.8"

services:
  model_serving:
    container_name: model_serving
    build:
      context: ../..
      dockerfile: ./docker/model_serving/Dockerfile
    env_file:
      - ../../.env
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:8000
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_ALIAS=${MODEL_ALIAS}
      - DEVICE=${DEVICE}
    volumes:
      - type: bind
        source: ../../app/cache
        target: /backend/app/cache
      - type: bind
        source: ../../app/logs
        target: /backend/app/logs
    ports:
      - ${PORT}:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python3", "server.py"]
