version: "3.8"

services:
  model_serving:
    container_name: model_serving
    build:
      context: ../..
      dockerfile: ./docker/model_serving/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - type: bind
        source: ../../data_source
        target: /backend/data_source
      - type: bind
        source: ../../logs
        target: /backend/logs
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "src/model_serving.py"]
  
volumes:
  data_source:
  logs: