version: "3.8"

services:
  model_serving:
    container_name: model_serving
    build:
      context: ../..
      dockerfile: ./docker/model_serving/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - /data_source:/data_source
      - /logs:/logs
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "src/model_serving.py"]