version: "3.8"

services:
  model_serving:
    container_name: model_serving
    build:
      context: ../..
      dockerfile: ./docker/model_serving/Dockerfile
    env_file:
      - ../../.env
    environment:
      - MODEL_CONFIG=${MODEL_CONFIG}
      - MLFLOW_TRACKING_URI=http://host.docker.internal:8000
    volumes:
      - type: bind
        source: ../../data_source
        target: /backend/data_source
      - type: bind
        source: ../../logs
        target: /backend/logs
      - type: bind
        source: ../../src/config
        target: /backend/src/config
    ports:
      - ${PORT}:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "src/model_serving.py"]
  
volumes:
  data_source:
  logs:
  src: